name: "Setup"
description: "Setup the runner and prepare the git repo"
inputs:
  llvm-subset:
    description: If a a minimal subset of the llvm-project monorepo should be cloned
    required: false
    default: 'false'
  setup-venv:
    description: If the venv should be set up
    required: false
    default: 'true'
  build-dependencies:
    description: If the dependencies required for a build should be installed
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Clone llvm subset
      if: ${{ inputs.llvm-subset != 'false' }}
      shell: bash
      run: ferrocene/ci/scripts/clone-llvm-subset.sh
    - name: Checkout submodules
      shell: bash
      run: ferrocene/ci/scripts/checkout-submodules.sh
    - name: Change file modification time to be consistent
      shell: bash
      run: ferrocene/ci/scripts/reset-mtime-to-last-commit.sh

    - name: Install dependencies (Ubuntu)
      if: ${{ contains(runner.name, 'ubuntu') && inputs.build-dependencies != 'false' }}
      shell: bash
      run: sudo ferrocene/ci/scripts/setup-ubuntu.sh

    - name: Install dependencies (Windows)
      if: contains(runner.name, 'windows') && inputs.build-dependencies
      shell: bash
      run: sudo ferrocene/ci/scripts/setup-windows.sh

    - name: Install dependencies (macOS)
      if: contains(runner.name, 'macos') && inputs.build-dependencies
      shell: bash
      run: sudo ferrocene/ci/scripts/setup-darwin.sh

    - name: Setup uv, Python, and venv
      if: ${{ inputs.setup-venv != 'false' }}
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv python install 3.12
        uv venv
        uv pip sync requirements.txt
