name: "Run (with or without container)"
description: "Run in a container, or not."
inputs:
  container:
    description: The container address
  script:
    description: The container address

runs:
  using: "composite"
  steps:
    - name: Run
      if: inputs.container == '' && steps.check.outputs.state != 'hit'
      shell: bash
      env:
        SCRIPT: ${{ inputs.script }}
      run: ferrocene/ci/run.sh

    - name: Run in container
      if: inputs.container != '' && steps.check.outputs.state != 'hit'
      shell: bash
      env:
        SCRIPT: ${{ inputs.script }}
      run: |
        docker run \
          --rm \
          --interactive \
          --env CI \
          --env SCRIPT \
          --env FERROCENE_HOST \
          --env FERROCENE_TARGETS \
          --env OUTSIDE_FERROUS \
          --env LLVM_BUILD_PARALLELISM \
          --workdir /home/ci/project \
          --mount "type=bind,src=$(pwd),dst=/home/ci/project" \
          --user $(id -u):$(id -g) \
          --network host \
          ${{ inputs.container }} \
          ferrocene/ci/run.sh

