name: "Run (with or without container)"
description: "Run in a container, or not."
inputs:
  container:
    description: The container address
  script:
    description: The script to run
  test-device-addr:
    description: The test device address to use

runs:
  using: "composite"
  steps:
    - name: Run
      if: ${{ inputs.container == '' }}
      shell: bash
      env:
        SCRIPT: ${{ inputs.script }}
      run: ferrocene/ci/run.sh

    - name: Run in container
      if: ${{ inputs.container != '' }}
      shell: bash
      env:
        SCRIPT: ${{ inputs.script }}
        TEST_DEVICE_ADDR: ${{ inputs.test-device-addr }}
      run: |
        docker run \
          --rm \
          --interactive \
          --env CI \
          --env SCRIPT \
          --env FERROCENE_HOST \
          --env FERROCENE_TARGETS \
          --env OUTSIDE_FERROUS \
          --env LLVM_BUILD_PARALLELISM \
          --env TEST_DEVICE_ADDR \
          --workdir /home/ci/project \
          --mount "type=bind,src=$(pwd),dst=/home/ci/project" \
          --user $(id -u):$(id -g) \
          --network host \
          ${{ inputs.container }} \
          ferrocene/ci/run.sh

