name: "Download QNX deployment"
description: "Fetch a QNX deployment"
inputs:
  version:
    description: The QNX version and BuildID (eg '7.1.0-472' for 7.1.0 BuildID 472)

runs:
  using: "composite"
  steps:
    - name: Calculate QNX filename
      id: calculate
      shell: bash
      env:
        FILENAME: qnx-deployment-${{ inputs.version }}.tar.zst
      run: |
        echo "filename=$FILENAME" >> $GITHUB_OUTPUT
    - name: Download QNX deployment
      shell: bash
      run: |
        az storage blob download \
          --name ${{ steps.calculate.filename }} \
          --container-name qnx \
          --account-name ferroceneci \
          --auth-mode login \
          --file ${{ steps.calculate.filename }}
    - name: Unpack the QNX deployment
      shell: bash
      run: |
        uv run ferrocene/ci/scripts/cache.py retrieve ${{ steps.calculate.filename }} .
    - name: Remove downloaded artifact
      shell: bash
      run: |
        rm -rf ${{ steps.calculate.filename }}