name: Build host
run-name: Build host (${{inputs.host-triple}})

on:
  workflow_call:
    inputs:
      host-triple:
        type: string
        description: The Rust triple of the host platform
      build-triples:
        type: string
        description: Additional Rust triples to build using this platform
      runner:
        type: string
        description: The GitHub Runner to run on
      environment:
        type: string
    outputs:
      cached-llvm:
        description: The URI of the (pre-cached or new built, then cached) llvm.tar.zst
        value: ${{ jobs.llvm.outputs.uri }}


jobs:
  llvm:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    outputs:
      uri: ${{ steps.build-llvm.outputs.uri }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup/
      # - name: Setup Azure
      #   uses: ./.github/actions/setup-azure/
      #   with:
      #     client-id: ${{ secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
      #     tenant-id: ${{ secrets.AZURE_OIDC_GHA_DIRECTORY_ID_TRYING }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build
        id: build-llvm
        run: |
          echo "llvm goes here"
          echo "uri=some://cache.url/for/testing" >> "$GITHUB_OUTPUT"
        
  build:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    needs: [llvm]
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
      artifact-url: ${{ steps.artifact.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/
      # - name: Setup Azure
      #   uses: ./.github/actions/setup-azure/
      #   with:
      #     client-id: ${{ secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
      #     tenant-id: ${{ secrets.AZURE_OIDC_GHA_DIRECTORY_ID_TRYING }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: |
          echo "got llvm from ${{ needs.llvm.outputs.uri }}"
          echo "build goes here"
          mkdir build
          touch build/boop
      - uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: build-${{inputs.host-triple}}
          path: build
  dist:
    runs-on: ${{ inputs.runner }}
    needs: [build]
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
      artifact-url: ${{ steps.artifact.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/
      # - name: Setup Azure
      #   uses: ./.github/actions/setup-azure/
      #   with:
      #     client-id: ${{ secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
      #     tenant-id: ${{ secrets.AZURE_OIDC_GHA_DIRECTORY_ID_TRYING }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-id }}
      - run: |
          echo "dist goes here"
          mkdir build
          touch build/boop
      - uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: dist-${{inputs.host-triple}}
          path: build
  # dist-tools:
  #   runs-on: ${{ inputs.runner }}
  #   needs: [build]
  #   steps:
  #     # - uses: actions/checkout@v4
  #     # - uses: ./.github/actions/setup/
  #     - run: echo "test"
  # self-test:
  #   runs-on: ${{ inputs.runner }}
  #   needs:
  #     - dist
  #   steps:
  #     # - uses: actions/checkout@v4
  #     #   with:
  #     #     submodules: false
  #     # - uses: ./.github/actions/setup/
  #     #   with:
  #     #     qnx: true
  #     - run: echo "test"