name: Container
run-name: Container (${{inputs.name}})

on:
  workflow_call:
    inputs:
      name:
        type: string
        description: The name of the container image
      architecture:
        # `choice` is not valid here: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
        type: string
        description: The architecture (x86_64 or aarch64)
      runner:
        type: string
        description: The GitHub Runner to run on (Linux only)
      environment:
        type: string
    outputs:
      run-id:
        description: The id of the workflow run
        value: ${{ github.run_id }}
      uri:
        description: The uri of the container
        value: ${{ jobs.container.outputs.uri }}


jobs: 
  container:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    outputs:
      uri: ${{ steps.container.outputs.uri }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup/
      - name: Setup Azure
        uses: ./.github/actions/setup-azure/
        with:
          client-id: ${{ (github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/hoverbear/gha-migration') && secrets.AZURE_OIDC_GHA_CLIENT_ID_STAGING || secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - id: container
        run: |
          uv run ./ferrocene/ci/scripts/container.py ensure-built ${{ inputs.architecture }} ${{ inputs.name }} --pull
          echo "uri=$(uv run ./ferrocene/ci/scripts/container.py uri ${{ inputs.architecture }} ${{ inputs.name }})" >> "$GITHUB_OUTPUT"