name: "Full"

on:
  push:
    branches:
      - trying
      - staging
      - hoverbear/gha-migration

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# One job per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-x86_64-unknown-linux-gnu:
    name: Build (x86_64-unknown-linux-gnu)
    uses: ./.github/workflows/host/build.yml
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      runner: ubuntu-latest

  dist-x86_64-unknown-linux-gnu:
    name: Dist (x86_64-unknown-linux-gnu)
    uses: ./.github/workflows/host/dist.yml
    needs:
      - build-x86_64-unknown-linux-gnu
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      runner: ubuntu-latest
      build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}

  build-x86_64-pc-windows-msvc:
    name: Build (x86_64-pc-windows-msvc)
    uses: ./.github/workflows/host/build.yml
    secrets: inherit
    with:
      host-triple: x86_64-pc-windows-msvc
      runner: windows-latest

  dist-x86_64-pc-windows-msvc:
    name: Build (x86_64-pc-windows-msvc)
    uses: ./.github/workflows/host/dist.yml
    needs:
      - build-x86_64-pc-windows-msvc
    secrets: inherit
    with:
      host-triple: x86_64-pc-windows-msvc
      runner: windows-latest
      build-run-id: ${{ needs.build-x86_64-pc-windows-msvc.outputs.run-id }}