name: "Full"

on:
  push:
    branches:
      - trying
      - staging
      - hoverbear/gha-migration

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# One job per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}


jobs:
  x86_64-unknown-linux-gnu:
    uses: ./.github/workflows/build-host.yml
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      runner: ubuntu-latest

  x86_64-pc-windows-msvc:
    uses: ./.github/workflows/build-host.yml
    secrets: inherit
    with:
      host-triple: x86_64-pc-windows-msvc
      runner: windows-latest