name: "Full"

on:
  push:
    branches:
      - trying
      - staging
      - hoverbear/gha-migration

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# One job per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # Matrix cannot be used here as later jobs will `need` specific containers
  # and we do not want to make those jobs wait for all containers.
  container-x86_64-ubuntu-24:
    name: Container (x86_64, ubuntu-24)
    uses: ./.github/workflows/container.yml
    secrets: inherit
    with:
      name: ubuntu-24
      architecture: x86_64
      runner: ubuntu-24.04

  build-x86_64-unknown-linux-gnu:
    name: Build (x86_64-unknown-linux-gnu)
    needs:
      - container-x86_64-ubuntu-24
    uses: ./.github/workflows/host-build.yml
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      runner: ubuntu-24.04
      container: ${{ needs.container-x86_64-ubuntu-24.outputs.uri }}

  dist-x86_64-unknown-linux-gnu:
    name: Dist (x86_64-unknown-linux-gnu)
    uses: ./.github/workflows/host-dist.yml
    needs:
      - container-x86_64-ubuntu-24
      - build-x86_64-unknown-linux-gnu
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      runner: ubuntu-24.04
      build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
      build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
      container: ${{ needs.container-x86_64-ubuntu-24.outputs.uri }}

  test-x86_64-unknown-linux-gnu:
    name: Test (x86_64-unknown-linux-gnu)
    uses: ./.github/workflows/host-test.yml
    needs:
      - container-x86_64-ubuntu-24
      - build-x86_64-unknown-linux-gnu
      - targets
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      runner: ubuntu-24.04
      build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
      build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
      container: ${{ needs.container-x86_64-ubuntu-24.outputs.uri }}

  doc-x86_64-unknown-linux-gnu:
    name: Doc (x86_64-unknown-linux-gnu)
    uses: ./.github/workflows/host-doc.yml
    needs:
      - container-x86_64-ubuntu-24
      - build-x86_64-unknown-linux-gnu
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      runner: ubuntu-24.04
      build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
      build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
      container: ${{ needs.container-x86_64-ubuntu-24.outputs.uri }}

  targets:
    name: Build additional targets
    uses: ./.github/workflows/targets.yml
    needs:
      - container-x86_64-ubuntu-24
      - build-x86_64-unknown-linux-gnu
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      triples: >
        aarch64-unknown-none,
        thumbv7em-none-eabi,
        thumbv7em-none-eabihf,
        armv8r-none-eabihf,
        wasm32-unknown-unknown,
        armv7r-none-eabihf,
        armebv7r-none-eabihf
      runner: ubuntu-24.04
      build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
      build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
      container: ${{ needs.container-x86_64-ubuntu-24.outputs.uri }}

  build-x86_64-pc-windows-msvc:
    name: Build (x86_64-pc-windows-msvc)
    uses: ./.github/workflows/host-build.yml
    secrets: inherit
    with:
      host-triple: x86_64-pc-windows-msvc
      runner: windows-2022

  dist-x86_64-pc-windows-msvc:
    name: Dist (x86_64-pc-windows-msvc)
    uses: ./.github/workflows/host-dist.yml
    needs:
      - build-x86_64-pc-windows-msvc
    secrets: inherit
    with:
      host-triple: x86_64-pc-windows-msvc
      runner: windows-2022
      build-run-id: ${{ needs.build-x86_64-pc-windows-msvc.outputs.run-id }}
      build-artifact: ${{ needs.build-x86_64-pc-windows-msvc.outputs.artifact-build }}

  test-x86_64-pc-windows-msvc:
    name: Test (x86_64-pc-windows-msvc)
    uses: ./.github/workflows/host-test.yml
    needs:
      - build-x86_64-pc-windows-msvc
      - targets
    secrets: inherit
    with:
      host-triple: x86_64-pc-windows-msvc
      runner: windows-2022
      build-run-id: ${{ needs.build-x86_64-pc-windows-msvc.outputs.run-id }}
      build-artifact: ${{ needs.build-x86_64-pc-windows-msvc.outputs.artifact-build }}


  build-aarch64-apple-darwin:
    name: Build (aarch64-apple-darwin)
    uses: ./.github/workflows/host-build.yml
    secrets: inherit
    with:
      host-triple: aarch64-apple-darwin
      runner: macos-14

  dist-aarch64-apple-darwin:
    name: Dist (aarch64-apple-darwin)
    uses: ./.github/workflows/host-dist.yml
    needs:
      - build-aarch64-apple-darwin
    secrets: inherit
    with:
      host-triple: aarch64-apple-darwin
      runner: macos-14
      build-run-id: ${{ needs.build-aarch64-apple-darwin.outputs.run-id }}
      build-artifact: ${{ needs.build-aarch64-apple-darwin.outputs.artifact-build }}

  test-aarch64-apple-darwin:
    name: Test (aarch64-apple-darwin)
    uses: ./.github/workflows/host-test.yml
    needs:
      - build-aarch64-apple-darwin
      - targets
    secrets: inherit
    with:
      host-triple: aarch64-apple-darwin
      runner: macos-14
      build-run-id: ${{ needs.build-aarch64-apple-darwin.outputs.run-id }}
      build-artifact: ${{ needs.build-aarch64-apple-darwin.outputs.artifact-build }}
  
  tracability-matrix:
    name: Tracability Matrix
    needs:
      - container-x86_64-ubuntu-24
      - build-x86_64-unknown-linux-gnu
      - test-x86_64-unknown-linux-gnu
      - test-x86_64-pc-windows-msvc
      - test-aarch64-apple-darwin
    runs-on: ubuntu-24.04
    env:
      artifact: tracability-matrix
    outputs:
      artifact-name: ${{ env.artifact }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup
      #   uses: ./.github/actions/setup/
      # - name: Setup Azure
      #   uses: ./.github/actions/setup-azure/
      #   with:
      #     client-id: ${{ secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
      #     tenant-id: ${{ secrets.AZURE_OIDC_GHA_DIRECTORY_ID_TRYING }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
          run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
      - run: |
          echo "tracability-matrix goes here"
          mkdir build
          touch build/boop
      - uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: ${{ env.artifact }}
          path: build
          retention-days: 1