name: "Full"

on:
  push:
    branches:
      - trying
      - staging
      - hoverbear/gha-migration

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# One job per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # Matrix cannot be used here as later jobs will `need` specific containers
  # and we do not want to make those jobs wait for all containers.
  container-x86_64-ubuntu-20:
    name: Container (x86_64, ubuntu-20)
    uses: ./.github/workflows/container.yml
    secrets: inherit
    with:
      name: ubuntu-20
      architecture: x86_64
      runner: ubuntu-24.04

  container-x86_64-ubuntu-24:
    name: Container (x86_64, ubuntu-24)
    uses: ./.github/workflows/container.yml
    secrets: inherit
    with:
      name: ubuntu-24
      architecture: x86_64
      runner: ubuntu-24.04

  build-x86_64-unknown-linux-gnu:
    name: Build (x86_64-unknown-linux-gnu)
    needs:
      - container-x86_64-ubuntu-20
    uses: ./.github/workflows/host-build.yml
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      runner: 8core-x86_64-unknown-linux-gnu
      container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}

  # dist-x86_64-unknown-linux-gnu:
  #   name: Dist (x86_64-unknown-linux-gnu)
  #   uses: ./.github/workflows/host-dist.yml
  #   needs:
  #     - container-x86_64-ubuntu-20
  #     - build-x86_64-unknown-linux-gnu
  #   secrets: inherit
  #   with:
  #     host-triple: x86_64-unknown-linux-gnu
  #     runner: 8core-x86_64-unknown-linux-gnu
  #     build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
  #     build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
  #     container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}

  test-x86_64-unknown-linux-gnu:
    name: Test (x86_64-unknown-linux-gnu)
    uses: ./.github/workflows/test.yml
    needs:
      - container-x86_64-ubuntu-20
      - build-x86_64-unknown-linux-gnu
      # - targets
    secrets: inherit
    with:
      triple: x86_64-unknown-linux-gnu
      host-triple: x86_64-unknown-linux-gnu
      runner: 8core-x86_64-unknown-linux-gnu
      build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
      build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
      container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}

  # doc:
  #   name: Doc
  #   uses: ./.github/workflows/doc.yml
  #   needs:
  #     - container-x86_64-ubuntu-20
  #     - build-x86_64-unknown-linux-gnu
  #   secrets: inherit
  #   with:
  #     host-triple: x86_64-unknown-linux-gnu
  #     runner: 8core-x86_64-unknown-linux-gnu
  #     build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
  #     build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
  #     container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}

  # source:
  #   name: Source
  #   uses: ./.github/workflows/source.yml
  #   needs:
  #     - container-x86_64-ubuntu-20
  #     - build-x86_64-unknown-linux-gnu
  #   secrets: inherit
  #   with:
  #     host-triple: x86_64-unknown-linux-gnu
  #     runner: 8core-x86_64-unknown-linux-gnu
  #     build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
  #     build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
  #     container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}

  targets:
    name: Build additional targets
    uses: ./.github/workflows/targets.yml
    needs:
      - container-x86_64-ubuntu-20
      - build-x86_64-unknown-linux-gnu
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      # Do not try to break this up into multiple lines. YAML is not your friend.
      triples: "aarch64-unknown-none,thumbv7em-none-eabi,thumbv7em-none-eabihf,armv8r-none-eabihf,wasm32-unknown-unknown,armv7r-none-eabihf,armebv7r-none-eabihf,aarch64-unknown-nto-qnx710,x86_64-pc-nto-qnx710"
      runner: 8core-x86_64-unknown-linux-gnu
      build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
      build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
      container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}

  # test-aarch64-unknown-ferrocenecoretest:
  #   name: Test (aarch64-unknown-ferrocenecoretest by x86_64-unknown-linux-gnu)
  #   uses: ./.github/workflows/test.yml
  #   needs:
  #     - container-x86_64-ubuntu-20
  #     - build-x86_64-unknown-linux-gnu
  #     - targets
  #   secrets: inherit
  #   with:
  #     test-host-tools: false
  #     test-std: false
  #     triple: aarch64-unknown-ferrocenecoretest
  #     # In the old CircleCI jobs, we did not pass this...
  #     # When this is enabled, we experienced test failures where it was
  #     # trying to test the x86_64 artifacts in CI
  #     host-triple: "" # x86_64-unknown-linux-gnu
  #     runner: 8core-x86_64-unknown-linux-gnu
  #     build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
  #     build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
  #     container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}
  #     test-device-addr: "127.0.0.1:12345"
  #     emulator-container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}
  #     emulator-prepare-command: ferrocene/ci/scripts/emulated-aarch64-test-runner.sh prepare
  #     emulator-start-command: ferrocene/ci/scripts/emulated-aarch64-test-runner.sh

  # test-x86_64-pc-nto-qnx710:
  #   name: Test (x86_64-pc-nto-qnx710 by x86_64-unknown-linux-gnu)
  #   uses: ./.github/workflows/test.yml
  #   needs:
  #     - container-x86_64-ubuntu-20
  #     - container-x86_64-ubuntu-24
  #     - build-x86_64-unknown-linux-gnu
  #     - targets
  #   secrets: inherit
  #   with:
  #     test-host-tools: false
  #     test-std: true
  #     triple: x86_64-pc-nto-qnx710
  #     # In the old CircleCI jobs, we did not pass this...
  #     # When this is enabled, we experienced test failures where it was
  #     # trying to test the x86_64 artifacts in CI
  #     host-triple: "" # x86_64-unknown-linux-gnu
  #     runner: 8core-x86_64-unknown-linux-gnu
  #     build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
  #     build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
  #     container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}
  #     test-device-addr: "172.31.1.11:12345"
  #     emulator-container: ${{ needs.container-x86_64-ubuntu-24.outputs.uri }}
  #     emulator-prepare-command: ./ferrocene/ci/scripts/emulated-x86_64-qnx-test-runner.sh prepare
  #     emulator-start-command: ./ferrocene/ci/scripts/emulated-x86_64-qnx-test-runner.sh
  #     qnx-version: "7.1.0-472"

  # test-aarch64-unknown-nto-qnx710:
  #   name: Test (aarch64-unknown-nto-qnx710 by x86_64-unknown-linux-gnu)
  #   uses: ./.github/workflows/test.yml
  #   needs:
  #     - container-x86_64-ubuntu-20
  #     - container-x86_64-ubuntu-24
  #     - build-x86_64-unknown-linux-gnu
  #     - targets
  #   secrets: inherit
  #   with:
  #     test-host-tools: false
  #     test-std: true
  #     triple: aarch64-unknown-nto-qnx710
  #     # In the old CircleCI jobs, we did not pass this...
  #     # When this is enabled, we experienced test failures where it was
  #     # trying to test the x86_64 artifacts in CI
  #     host-triple: "" # x86_64-unknown-linux-gnu
  #     runner: 8core-x86_64-unknown-linux-gnu
  #     build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
  #     build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}
  #     container: ${{ needs.container-x86_64-ubuntu-20.outputs.uri }}
  #     test-device-addr: "172.31.1.105:12345"
  #     emulator-container: ${{ needs.container-x86_64-ubuntu-24.outputs.uri }}
  #     emulator-prepare-command: ./ferrocene/ci/scripts/emulated-aarch64-qnx-test-runner.sh prepare
  #     emulator-start-command: ./ferrocene/ci/scripts/emulated-aarch64-qnx-test-runner.sh
  #     qnx-version: "7.1.0-472"

  # build-x86_64-pc-windows-msvc:
  #   name: Build (x86_64-pc-windows-msvc)
  #   uses: ./.github/workflows/host-build.yml
  #   secrets: inherit
  #   with:
  #     host-triple: x86_64-pc-windows-msvc
  #     runner: 8core-x86_64-pc-windows-msvc

  # dist-x86_64-pc-windows-msvc:
  #   name: Dist (x86_64-pc-windows-msvc)
  #   uses: ./.github/workflows/host-dist.yml
  #   needs:
  #     - build-x86_64-pc-windows-msvc
  #   secrets: inherit
  #   with:
  #     host-triple: x86_64-pc-windows-msvc
  #     runner: 8core-x86_64-pc-windows-msvc
  #     build-run-id: ${{ needs.build-x86_64-pc-windows-msvc.outputs.run-id }}
  #     build-artifact: ${{ needs.build-x86_64-pc-windows-msvc.outputs.artifact-build }}

  # test-x86_64-pc-windows-msvc:
  #   name: Test (x86_64-pc-windows-msvc)
  #   uses: ./.github/workflows/test.yml
  #   needs:
  #     - build-x86_64-pc-windows-msvc
  #     # - targets
  #   secrets: inherit
  #   with:
  #     triple: x86_64-pc-windows-msvc
  #     host-triple: x86_64-pc-windows-msvc
  #     runner: 8core-x86_64-pc-windows-msvc
  #     build-run-id: ${{ needs.build-x86_64-pc-windows-msvc.outputs.run-id }}
  #     build-artifact: ${{ needs.build-x86_64-pc-windows-msvc.outputs.artifact-build }}


  # build-aarch64-apple-darwin:
  #   name: Build (aarch64-apple-darwin)
  #   uses: ./.github/workflows/host-build.yml
  #   secrets: inherit
  #   with:
  #     host-triple: aarch64-apple-darwin
  #     runner: macos-14-xlarge

  # dist-aarch64-apple-darwin:
  #   name: Dist (aarch64-apple-darwin)
  #   uses: ./.github/workflows/host-dist.yml
  #   needs:
  #     - build-aarch64-apple-darwin
  #   secrets: inherit
  #   with:
  #     host-triple: aarch64-apple-darwin
  #     runner: macos-14-xlarge
  #     build-run-id: ${{ needs.build-aarch64-apple-darwin.outputs.run-id }}
  #     build-artifact: ${{ needs.build-aarch64-apple-darwin.outputs.artifact-build }}

  # test-aarch64-apple-darwin:
  #   name: Test (aarch64-apple-darwin)
  #   uses: ./.github/workflows/test.yml
  #   needs:
  #     - build-aarch64-apple-darwin
  #     # - targets
  #   secrets: inherit
  #   with:
  #     triple: aarch64-apple-darwin
  #     host-triple: aarch64-apple-darwin
  #     runner: macos-14-xlarge
  #     build-run-id: ${{ needs.build-aarch64-apple-darwin.outputs.run-id }}
  #     build-artifact: ${{ needs.build-aarch64-apple-darwin.outputs.artifact-build }}
  
  traceability-matrix:
    name: Tracability Matrix
    uses: ./.github/workflows/traceability-matrix.yml
    needs:
      - container-x86_64-ubuntu-20
      - build-x86_64-unknown-linux-gnu
      - test-x86_64-unknown-linux-gnu
      # - test-aarch64-unknown-ferrocenecoretest
      # - test-x86_64-pc-nto-qnx710
      # - test-aarch64-unknown-nto-qnx710
      # - test-x86_64-pc-windows-msvc
      # - test-aarch64-apple-darwin
    secrets: inherit
    with:
      host-triple: x86_64-unknown-linux-gnu
      runner: 8core-x86_64-unknown-linux-gnu
      build-run-id: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.run-id }}
      build-artifact: ${{ needs.build-x86_64-unknown-linux-gnu.outputs.artifact-build }}   