name: Build host
run-name: Build (${{inputs.host-triple}})

on:
  workflow_call:
    inputs:
      host-triple:
        type: string
        description: The Rust triple of the host platform
      runner:
        type: string
        description: The GitHub Runner to run on
      environment:
        type: string
    outputs:
      run-id:
        description: The id of the workflow run
        value: ${{ github.run_id }}
      cache-llvm:
        description: The URI of the (pre-cached or new built, then cached) llvm.tar.zst
        value: ${{ jobs.llvm.outputs.uri }}
      artifact-build:
        description: The name of the build job artifact
        value: ${{ jobs.build.outputs.artifact-name }}


jobs:
  llvm:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    outputs:
      uri: ${{ steps.build-llvm.outputs.uri }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup
      #   uses: ./.github/actions/setup/
      # - name: Setup Azure
      #   uses: ./.github/actions/setup-azure/
      #   with:
      #     client-id: ${{ secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
      #     tenant-id: ${{ secrets.AZURE_OIDC_GHA_DIRECTORY_ID_TRYING }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build
        id: build-llvm
        run: |
          echo "llvm goes here"
          echo "uri=some://cache.url/for/testing" >> "$GITHUB_OUTPUT"
        
  build:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    needs: [llvm]
    env:
      artifact: build-${{inputs.host-triple}}
    outputs:
      artifact-name: ${{ env.artifact }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup
      #   uses: ./.github/actions/setup/
      # - name: Setup Azure
      #   uses: ./.github/actions/setup-azure/
      #   with:
      #     client-id: ${{ secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
      #     tenant-id: ${{ secrets.AZURE_OIDC_GHA_DIRECTORY_ID_TRYING }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: |
          echo "got llvm from ${{ needs.llvm.outputs.uri }}"
          echo "build goes here"
          mkdir build
          touch build/boop
      - uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: ${{ env.artifact }}
          path: build