name: Build host
run-name: Build (${{inputs.host-triple}})

on:
  workflow_call:
    inputs:
      host-triple:
        type: string
        description: The Rust triple of the host platform
      runner:
        type: string
        description: The GitHub Runner to run on
      container:
        type: string
        description: The container URI to run the build in, if any (Linux only)
      environment:
        type: string
    outputs:
      run-id:
        description: The id of the workflow run
        value: ${{ github.run_id }}
      cache-llvm:
        description: The URI of the (pre-cached or new built, then cached) llvm.tar.zst
        value: ${{ jobs.llvm.outputs.uri }}
      artifact-build:
        description: The name of the build job artifact
        value: ${{ jobs.build.outputs.artifact-name }}


jobs:
  llvm:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    outputs:
      uri: ${{ steps.store.outputs.uri }}
    env:
      FERROCENE_HOST: ${{ inputs.host-triple }}
      SCRIPT: ferrocene/ci/scripts/llvm_cache.py prepare --url llvm_cache.tar.zst
      # This tries to strike a balance between the highest concurrency possible
      # and not running out of memory during a build. If building LLVM fails
      # due to the OOM killer killing the build, decrease this number.
      LLVM_BUILD_PARALLELISM: 18
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup/

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ (github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/hoverbear/gha-migration') && secrets.AZURE_OIDC_GHA_CLIENT_ID_STAGING || secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Authenicate docker with Azure
        if: runner.os == 'Linux'
        run: az acr login --name ferrocenecr

      - name: Run
        if: inputs.container == ''
        shell: bash
        run: uv run bash ferrocene/ci/run.sh

      - name: Run in container
        if: inputs.container != ''
        shell: bash
        run: |
          docker run \
            --rm \
            --interactive \
            --env SCRIPT \
            --env FERROCENE_HOST \
            --env LLVM_BUILD_PARALLELISM \
            --workdir /home/ci/project \
            --mount "type=bind,src=$(pwd),dst=/home/ci/project" \
            --user $(id -u):$(id -g) \
            --network host \
            ${{ inputs.container }}
            uv run bash ferrocene/ci/run.sh

      - name: Store cache
        id: store
        shell: bash
        run: |
          set -e
          hash=$(uv run ferrocene/ci/scripts/llvm_cache.py hash)
          uri=https://ferroceneci.blob.core.windows.net/ferrocene-llvm-cache/${{ inputs.host-triple }}-$hash.tar.zst
          az storage copy -s llvm_cache.tar.zst -d $uri
          echo "uri=$uri" >> $GITHUB_OUTPUT
        
  build:
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    needs:
      - llvm
    env:
      ARTIFACT: build-${{inputs.host-triple}}
      FERROCENE_HOST: x86_64-unknown-linux-gnu
      FERROCENE_TARGETS: aarch64-unknown-linux-gnu
      SCRIPT: |
        echo "Hello!"
    outputs:
      artifact-name: ${{ env.ARTIFACT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup/

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ (github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/hoverbear/gha-migration') && secrets.AZURE_OIDC_GHA_CLIENT_ID_STAGING || secrets.AZURE_OIDC_GHA_CLIENT_ID_TRYING }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Authenicate docker with Azure
        run: az acr login --name ferrocenecr

      - name: Get LLVM cache
        shell: bash
        run: |
          az storage copy -s $uri -d llvm_cache.tar.zst
          ferrocene/ci/scripts/llvm_cache.py download --url llvm_cache.tar.zst

      - name: Run
        if: inputs.container == ''
        shell: bash
        run: uv run ferrocene/ci/run.sh

      - name: Run in container
        if: inputs.container != ''
        shell: bash
        run: |
          docker run \
            --rm \
            --interactive \
            --env SCRIPT \
            --env FERROCENE_HOST \
            --workdir /home/ci/project \
            --mount "type=bind,src=$(pwd),dst=/home/ci/project" \
            --user $(id -u):$(id -g) \
            --network host \
            ${{ inputs.container }}
            uv run ferrocene/ci/run.sh

      - uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: ${{ env.ARTIFACT }}
          path: build